version: 2.1 # use CircleCI 2.0
orbs:
  cypress: cypress-io/cypress@2
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"     
workflows:
  build:
    jobs:
      - cypress/install:
          install-command: |
            yarn install
      - cypress/run:
          yarn: true
          name: "Integration Test"
          requires: 
            - cypress/install
          executor: with-chrome
          browser: chrome
          pre-steps:
            - run: yarn install
            - run: 
                command: yarn add cypress --dev
            - run: 
                command: yarn add multiple-cucumber-html-reporter --save-dev
            - run:
                command: mkdir -p ~/cucumber
            - run: 
                command: npx cypress run     
          post-steps:
            - run: 
                command: node cucumber-html-reports.js
          
