version: 2.1 # use CircleCI 2.0
orbs:
  cypress: cypress-io/cypress@2
jobs:     
  test:
    docker:
      - image: 'cypress/base:14'
    steps:
      - checkout
      - run:
          name: Install cypress 
          command: |
            npm install --save-dev cypress
            npm i multiple-cucumber-html-reporter --save-dev
            mkdir -p test-report 
            npx cypress verify
            npx cypress run
            node cucumber-html-reports.js
            cp -r cypress/cucumber-reports test-report
      - run: 
          when: on_fail
          command: | 
            node cucumber-html-reports.js
            cp -r cypress/cucumber-reports test-report
      - store_test_results:
          path: test-report
      - store_artifacts:
          path: cypress/cucumber-reports
          destination: test-report
workflows:
  test:
    jobs:
      - test