version: 2.1 # use CircleCI 2.0
orbs:
  cypress: cypress-io/cypress@2
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"     
workflows:
  build:
    jobs:
      - cypress/install:
          install-command: yarn install
      - cypress/run:
          yarn: true
          name: "Integration Test"
          requires: 
            - cypress/install
          executor: with-chrome
          browser: chrome
          install-command: |
            yarn install
            yarn add cypress --dev
            yarn add multiple-cucumber-html-reporter --save-dev
            mkdir -p ~/cucumber    
          post-install:
            - run: npx cypress run 
            - run: node cucumber-html-reports.js
          
