version: 2.1 # use CircleCI 2.0
orbs:
  cypress: cypress-io/cypress@2
# executors:
#   with-chrome:
#     resource_class: small
jobs:     
  build:
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"
    steps:
      - run:
          name: Install cypress 
          command: |
            yarn add cypress --dev
            yarn add multiple-cucumber-html-reporter --save-dev
            npx cypress verify
  test:
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"
    steps:
      - run: 
          name: Run Cypress
          command: |
            cd QAAutomation-Int
            npx cypress run
      - store_test_results:
          path: test-results
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      # - cypress/install:
      #     install-command: yarn install
      # - cypress/run:
      #     yarn: true
      #     name: "Integration Test"
      #     requires: 
      #       - cypress/install
      #     executor: with-chrome
      #     browser: chrome
      #     install-command: |
      #       yarn install
      #       yarn add cypress --dev
      #       yarn add multiple-cucumber-html-reporter --save-dev
      #       mkdir -p /tmp/core_dumps 
      #       npx cypress run
      #     post-install:
      #       - run: node cucumber-html-reports.js
      #       - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #           path: test-results
      #       - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      #           path: test-results
      #           destination: /tmp/core_dumps
          
