version: 2.1 # use CircleCI 2.0
orbs:
  cypress: cypress-io/cypress@2
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"     
workflows:
  build:
    jobs:
      - cypress/install:
          install-command: |
            yarn install
      - cypress/run:
          yarn: true
          name: "Integration Test"
          install-command: 
            yarn add multiple-cucumber-html-reporter --save-dev
          requires: 
            - cypress/install
          executor: with-chrome
          browser: chrome
          command: |
            mkdir -p ~/cucumber
            npx cypress run
            node cucumber-html-reports.js