version: 2.1 # use CircleCI 2.0
orbs:
  cypress: cypress-io/cypress@2
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"

      # - run:
      #     name: Install cypress 
      #     command: |
      #       yarn install
      #       yarn add cypress --dev
      #       apt get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      #       yarn add multiple-cucumber-html-reporter --save-dev
      #       npx cypress verify
      #       mkdir -p test-report
      #       npx cypress run
      
workflows:
  build:
    jobs:
      - cypress/install:
          install-command: yarn install
      - cypress/run:
          yarn: true
          name: "Integration Test"
          executor: with-chrome
          browser: chrome
          install-command: |
            yarn install
            yarn add cypress --dev
            yarn add multiple-cucumber-html-reporter --save-dev
            mkdir -p test-report 
            npx cypress run
            node cucumber-html-reports.js
            cp -r cypress/cucumber-reports test-report
          post-install:
            - store_test_results:
                path: test-report
            - store_artifacts:
                path: test-report
          
